### ISSUE TITLE
登陆扫码显示“当前账号无法使用该服务”

### ISSUE THREAD

**Issue by happylilem** [sangbobo/WeChatKeyTips#1]
您好，我想使用这个库来获取微信团购群的关键消息，上海封闭的居民们太难了……我看这个库上次更新已经是五年前了，但还是不抱希望地来问一下，我运行run.py扫了自动生成的登陆二维码后显示“当前账号无法使用该服务”，请问可能的原因是什么？是否和微信版本更新有关？
若能收到回复真的感激不尽……

**Comment by sangbobo** [comment]
理论上能否使用取决于你的账号是否能使用微信网页版，https://wx.qq.com/
目前来说大部分账号都不能登陆了。

**Comment by sangbobo** [comment]
> 您好，我想使用这个库来获取微信团购群的关键消息，上海封闭的居民们太难了……我看这个库上次更新已经是五年前了，但还是不抱希望地来问一下，我运行run.py扫了自动生成的登陆二维码后显示“当前账号无法使用该服务”，请问可能的原因是什么？是否和微信版本更新有关？ 若能收到回复真的感激不尽……
